version: "3.1"
services:
  mongodbs:
    image: mongodb/mongodb-community-server
    ports:
      - "21091:27017"
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=${MONGODB_ADMIN_USERNAME}
      - MONGODB_INITDB_ROOT_PASSWORD=${MONGODB_ADMIN_PASSWORD}

